# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    vb.memory = 1024
  end


  config.vm.define "projenkins", autostart: false do |projenkins|
    projenkins.vm.hostname = "jenkins.pkdevops.com"
    projenkins.vm.network :private_network, ip: "192.168.251.26"
      config.vm.provision "shell", path: "environments/test/manifests/puppet.sh" 
      config.vm.provision "puppet" do |puppet|
         puppet.environment_path = "environments"
         puppet.environment = "test"
         puppet.options = "--verbose --debug"
      end
  end

  config.vm.define "nexus", autostart: false do |nexus|
    nexus.vm.hostname = "nexus.pkdevops.com"
    nexus.vm.network :private_network, ip: "192.168.251.27"
      config.vm.provision "shell", path: "environments/test/manifests/puppet.sh" 
      config.vm.provision "puppet" do |puppet|
         puppet.environment_path = "environments"
         puppet.environment = "test"
         puppet.options = "--verbose --debug"
      end
  end

end
